spring.datasource.url=jdbc:mysql://mysql-online-exam.alwaysdata.net:3306/online-exam_database
spring.datasource.username=436078
spring.datasource.password=Suresh@81050
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
server.port=8080